version: "3.5"
services:
  mysql:
    container_name: base-nestjs-sql
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    restart: "no"

  phpmyadmin:
    container_name: base-nestjs-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: "no"
    depends_on:
      - mysql