version: "3.5"
services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./scripts/wait-for-it.sh base-nestjs-mysql:3306 -- bash -c "yarn && yarn build && NODE_ENV=production yarn db:migrate && NODE_ENV=production yarn db:seed && yarn start:prod"
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .env.production:/base-nestjs/.env.production
    depends_on:
      - mysql

  mysql:
    container_name: base-nestjs-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped

  phpmyadmin:
    container_name: base-nestjs-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  # default directory on Ubuntu: /var/lib/docker/volumes
  mysql_volume:
    name: base-nestjs-mysql-prod-volume